language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
install: pip install coveralls testtools mock https://github.com/Dreae/httmock/archive/master.zip
script: coverage run setup.py test
after_success: coveralls
notifications:
  email:
    - dreae@dreae.me
